# Generated by Django 5.1.7 on 2025-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MBA', 'MBA')], max_length=50),
        ),
    ]
